- hosts: all

  sudo: yes

  tasks:
    - name: add nginx config to sites-available
      template: src=./nginx.conf.j2
                dest=/etc/nginx/sites-available/{{ inventory_hostname_short }}
      notify:
        - restart nginx

    - name: add symlink in nginx sites-enabled
      file: src=/etc/nginx/sites-available/{{ inventory_hostname_short }}
            dest=/etc/nginx/sites-enabled/{{ inventory_hostname_short }} state=link
      notify:
        - restart nginx
    
    - name: make sure nginx is running
      service: name=nginx state=running
   
  handlers:
    - name: restart nginx
      service:  name=nginx state=restarted
